- hosts: consul-hosts
  roles:
    - andrewrothstein.consul

- hosts: vault-masters

  any_errors_fatal: true
  become: yes
  become_user: root

  pre_tasks: 
    - name: install python
      yum:
        name: python
        state: present

    - name: install unzip
      yum:
        name: unzip
        state: present
 
    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgcheck: no
    
    - name: install pip
      yum:
        name: python-pip
        state: present
 
    - pip:
        name: virtualenv

    - pip:
        name: netaddr

  tasks:
 
  - include_role:
      name: brianshumate.vault

