---
- name: Copy password file to control machine
  fetch:
    src: "{{ pwfile }}"
    dest: "{{ global_cache_dir }}/consul.pw"
    fail_on_missing: no
    flat: yes
  changed_when: false

- name: Stat password file on control machine
  stat:
    path: "{{ global_cache_dir }}/consul.pw"
  register: controller_pwfile
  run_once: true
  changed_when: false
  become: no
  delegate_to: localhost

- name: Generate new password
  shell: "{{ gopath_consul }}/pkg/{{ controller_goos.stdout }}_{{ controller_goarch.stdout }}/consul keygen > {{ global_cache_dir }}/consul.pw"
  when: not controller_pwfile.stat.exists
  become: no
  run_once: true
  delegate_to: localhost

- name: Copy password files to all nodes
  copy:
    src: "{{ global_cache_dir }}/consul.pw"
    dest: "{{ pwfile }}"
    mode: 0200
    owner: root
    group: root

- name: Write password to variable
  set_fact:
    consul_encrypt: "{{ lookup('file', '{{ global_cache_dir }}/consul.pw') }}"
  changed_when: false

- name: Delete password file on control machine
  file:
    path: "{{ global_cache_dir }}/consul.pw"
    state: absent
  changed_when: false
