---
galaxy_info:
  author: Brian Shumate
  description: Vault server role
  company: your company (optional)
  license: license BSD
  min_ansible_version: 2.1.0.0
  platforms:
  - name: EL
    versions:
    - 6
    - 7
  #- name: SmartOS
  #  versions:
  #  - all
  #  - any
  #- name: FreeBSD
  #  versions:
  #  - 11.0
  - name: Ubuntu
    versions:
    - xenial
  - name: Debian
    versions:
    - jessie
  galaxy_tags:
  - networking
  - security
  - system
dependencies: []
