- hosts: consul-hosts
  roles:
    - role: consul
      consul_client_addr: 0.0.0.0
      consul_group: "{{ groups['consul'] }}"


- hosts: vault-masters

  pre_tasks: 
    - name: install python
      yum:
        name: python
        state: present

    - name: install unzip
      yum:
        name: unzip
        state: present
 
    - name: Add repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
        gpgcheck: no
    
    - name: install pip
      yum:
        name: python-pip
        state: present
 
    - pip:
        name: virtualenv

    - pip:
        name: netaddr

    - name: Install Vault
      any_errors_fatal: true
      become: yes
      become_user: root
      roles:
          - { role: brianshumate.vault }
